dbcollection: dev
enable_trace_format_check: 0
segment_window: 1000000
real_time_segment_window: 600
uni_size: 0
is_metadata_in_cache_size: 0

nodes:
  - localhost

trace_files:
  - wiki2018.tr

cache_types:
  - LRB

